### ISSUE TITLE
Container doesn't exist

### ISSUE THREAD

**Issue by cgpu** [UMCUGenetics/MetaboShiny#30]
Hi there,

I read your [preprint on bioRxiv](https://www.biorxiv.org/content/10.1101/734236v1) and then tried to pull `jcwolthuis/metaboshiny` as I was eager to test. Currently the container is not available. 

Have you changed the name of the repo and/or image at Dockerhub?

Thanks in advance,
Christina

**Comment by poofcakes** [comment]
As an alternative, you should be able to clone the repo and use `docker build .` to build it from the Dockerfile for now. :)

![image](https://user-images.githubusercontent.com/8579642/63251893-fdb1f480-c26e-11e9-9976-4b3816c6b9e0.png)

**Comment by cgpu** [comment]
Thank you, image built successfully although it took a looong while :).

Best wishes for the upcoming official publication,
Christina

**Comment by joannawolthuis** [comment]
Hi there! First of all, thank you for your interest! I'm excited *and a bit nervous, haha* to see people come to the github page :D I saw that I put the github public, but not the docker, that should be fixed now! There are indeed quite some dependencies, which is why I wanted to spare users the build sequence, oof! Please share any issues with me, and a proper readme will be up ASAP once I get back from holidays next week :)

**Comment by cgpu** [comment]
Hi Joanna,

Thanks for such a wonderful job! Happy to see such an effort with solid Research Software Engineering best practices in mind! Happy to provide feedback once I give it a more hands on try.

Christina :)
